print ("Tutorial de como barrer una habitación.")
print ("Paso 1: Recoger toda la ropa y objetos utilizables del suelo")
print ("Paso 2: En caso de exitir bolsas y basura en el suelo, recoger y botar al basurero")
print ("Paso 3: Buscar escoba, recogedor y un vaso con agua")
print ("Paso 4: Rociar con un poco de agua el suelo de toda la habitación, esto ayudará a que el polvo no se suspenda en el ambiente")
print ("Paso 5: Agarrar la escoba y situarse en la esquina mas lejana a la puerta de ingreso")
print ("Paso 6: Empezar con el barrido de polvo en dirección a la puerta de ingreso")
print ("Paso 7: Revisar y barrer por debajo de muebles como ser escritorio, cama, mesas, sillas, etc.")
print ("Paso 8: Ir acumulando todo el polvo de la habitación en dirección a la puerta de ingreso")
print ("Paso 9: Una vez recorrido toda la habitación, agarrar el recogedor y empezar a depositar sobre este todo el polvo acumulado")
print ("Paso 10: Vaciar el recogedor sobre un contenedor de basura")
print ("Paso 11: Fin tutorial.")
